In [9]:
import pandas as pd
import datetime

year = datetime.datetime.now().year

urls = ["https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/.S.C+L.A.TO1.D+F.5J.A.BH+CN+CY+HK+ID+IN+JP+KR+MO+MY+PH+SA+SG+TR+TW.A.5J.N?format=csv"]

df = pd.concat([pd.read_csv(url) for url in urls])
col_use = ['L_POSITION','L_CURR_TYPE', 'L_REP_CTY','TIME_PERIOD','OBS_VALUE']
df2 = df[col_use].copy()
df2.replace({'D': 'D:Domestic currency (ie currency of bank location country)',
             'F': 'F:Foreign currency (ie currencies foreign to bank location country)',
             'L': 'L:Total liabilities',
             'C': 'C:Total claims'}, inplace=True)

# df1 = pd.read_excel(r"C:\Users\AhmadAizudeen\The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\SEACEN Faculty & Research - RSU\02_Requests\2025\2025.04.29 RM CYP presentation charts\raw data and figures\CY data\currency amount outstanding.xlsx", sheet_name='Sheet1')
rename_col = ['Balance sheet position', 'Currency', 'Reporting country', 'Period','Value']
df2 = df2.rename(columns={k:v for k,v in zip(df2.columns, rename_col)})

col = df2.columns.to_list()
# col
df2 = df2.groupby(by = ['Balance sheet position', 'Currency', 'Period']).sum()
df2.reset_index(inplace=True)
df2['Reporting country'] = 'Asia'
df2['Year'] = df2['Period'].apply(lambda x: str(x)[:4])
df2.drop(columns=['Period', 'Reporting country'], inplace=True)
df2 = df2.groupby(['Year', col[0], 'Currency']).sum()
df2.reset_index(inplace=True)
df2['Value'] = df2.apply(lambda row: row['Value'] if row['Balance sheet position'] == 'C:Total claims' else -row['Value'], axis=1)
change_year = df['TIME_PERIOD'].sort_values().unique()[-1]
df2.replace({change_year[:4]: change_year}, inplace=True)
df2 = df2[df2['Year'] >= '2000']
df2

,Year,Balance sheet position,Currency,Value
92,2000,C:Total claims,D:Domestic currency (ie currency of bank locat...,1.888666e+06
93,2000,C:Total claims,F:Foreign currency (ie currencies foreign to b...,6.211234e+06
94,2000,L:Total liabilities,D:Domestic currency (ie currency of bank locat...,-9.008830e+05
95,2000,L:Total liabilities,F:Foreign currency (ie currencies foreign to b...,-4.070971e+06
96,2001,C:Total claims,D:Domestic currency (ie currency of bank locat...,1.699528e+06
...,...,...,...,...
191,2024,L:Total liabilities,F:Foreign currency (ie currencies foreign to b...,-1.932508e+07
192,2025-Q2,C:Total claims,D:Domestic currency (ie currency of bank locat...,3.602153e+06
193,2025-Q2,C:Total claims,F:Foreign currency (ie currencies foreign to b...,1.875960e+07
194,2025-Q2,L:Total liabilities,D:Domestic currency (ie currency of bank locat...,-3.744805e+06
195,2025-Q2,L:Total liabilities,F:Foreign currency (ie currencies foreign to b...,-9.795928e+06

In [ ]:
import pandas as pd
import datetime

year = datetime.datetime.now().year

urls = ["https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/.S.C+L.A.TO1.D+F.5J.A.BH+CN+CY+HK+ID+IN+JP+KR+MO+MY+PH+SA+SG+TR+TW.A.5J.N?format=csv"]

[url for url in urls]

In [109]:
import plotly.express as px

fig = px.bar(
    df2,
    x="Year",
    y="Value",
    color="Currency",
)

fig.update_layout(
    plot_bgcolor='white',
    width=800,
    height=500,
    margin=dict(b=100),   # Extra bottom space
    legend=dict(
        orientation="h",
        y=-0.3,           # Move legend further down
        x=0.5,
        xanchor="center",
        yanchor="top"
    )
)

fig.add_annotation(
    xref="paper", yref="paper",
    x=0.02, y=0.1,
    text="(-) Liabilities",
    showarrow=False,
    font=dict(size=12)
)

fig.add_annotation(
    xref="paper", yref="paper",
    x=0.02, y=0.9,
    text="(+) Claims",
    showarrow=False,
    font=dict(size=12)
)

fig.update_yaxes(title_text=None)

fig.show()

In [3]:
import pandas as pd

urls = ["https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/.S.C+L.A.TO1.A.5J.A.BH+CN+CY+HK+ID+IN+JP+KR+MO+MY+PH+SA+SG+TR+TW.B+N.5J.N?format=csv"]

df = pd.concat([pd.read_csv(url) for url in urls])
col_use = ['L_POSITION','L_CP_SECTOR', 'L_REP_CTY','TIME_PERIOD','OBS_VALUE']
df2 = df[col_use].copy()
df2.replace({'B': 'B:Banks, total',
             'N': 'N:Non-banks, total',
             'L': 'L:Total liabilities',
             'C': 'C:Total claims'}, inplace=True)

# df1 = pd.read_excel(r"C:\Users\AhmadAizudeen\The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\SEACEN Faculty & Research - RSU\02_Requests\2025\2025.04.29 RM CYP presentation charts\raw data and figures\CY data\currency amount outstanding.xlsx", sheet_name='Sheet1')
rename_col = ['Balance sheet position', 'Counterparty sector', 'Reporting country', 'Period','Value']
df2 = df2.rename(columns={k:v for k,v in zip(df2.columns, rename_col)})

col = df2.columns.to_list()
# col
df2 = df2.groupby(by = ['Balance sheet position', 'Counterparty sector', 'Period']).sum()
df2.reset_index(inplace=True)
df2['Reporting country'] = 'Asia'
df2['Year'] = df2['Period'].apply(lambda x: str(x)[:4])
df2.drop(columns=['Period', 'Reporting country'], inplace=True)
df2 = df2.groupby(['Year', col[0], 'Counterparty sector']).sum()
df2.reset_index(inplace=True)
df2['Value'] = df2.apply(lambda row: row['Value'] if row['Balance sheet position'] == 'C:Total claims' else -row['Value'], axis=1)
change_year = df['TIME_PERIOD'].sort_values().unique()[-1]
df2.replace({change_year[:4]: change_year}, inplace=True)
df2 = df2[df2['Year'] >= '2000']
df2

        Year Balance sheet position Counterparty sector         Value
92      2000         C:Total claims      B:Banks, total  2.805821e+06
93      2000         C:Total claims  N:Non-banks, total  3.181684e+06
94      2000    L:Total liabilities      B:Banks, total -2.232355e+06
95      2000    L:Total liabilities  N:Non-banks, total -1.071175e+06
96      2001         C:Total claims      B:Banks, total  2.903479e+06
..       ...                    ...                 ...           ...
191     2024    L:Total liabilities  N:Non-banks, total -1.076189e+07
192  2025-Q2         C:Total claims      B:Banks, total  8.020094e+06
193  2025-Q2         C:Total claims  N:Non-banks, total  1.324103e+07
194  2025-Q2    L:Total liabilities      B:Banks, total -7.571315e+06
195  2025-Q2    L:Total liabilities  N:Non-banks, total -5.789176e+06

[104 rows x 4 columns]

In [8]:
df2.pivot(columns='Year', index=['Balance sheet position', 'Counterparty sector'], values='Value').reset_index()

Year,Balance sheet position,Counterparty sector,2000,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025-Q2
0,C:Total claims,"B:Banks, total",2805821.0,2903479.0,2614403.0,2525011.0,2612791.0,3072104.0,3335401.0,4926443.0,...,1.113456e+07,1.304366e+07,1.387458e+07,1.379873e+07,1.414895e+07,1.405917e+07,1.490337e+07,1.478030e+07,1.512475e+07,8.020094e+06
1,C:Total claims,"N:Non-banks, total",3181684.0,3215425.0,3363843.0,4010101.0,4637890.0,5684704.0,6577086.0,7853763.0,...,1.497364e+07,1.730920e+07,1.864604e+07,2.003310e+07,2.174073e+07,2.316658e+07,2.247059e+07,2.315424e+07,2.490955e+07,1.324103e+07
2,L:Total liabilities,"B:Banks, total",-2232355.0,-2304094.0,-2180007.0,-2277425.0,-2477970.0,-3026958.0,-3167892.0,-4242469.0,...,-1.149040e+07,-1.351973e+07,-1.439810e+07,-1.434750e+07,-1.502454e+07,-1.508717e+07,-1.479286e+07,-1.457358e+07,-1.512718e+07,-7.571315e+06
3,L:Total liabilities,"N:Non-banks, total",-1071175.0,-1085295.0,-1152539.0,-1237949.0,-1371256.0,-1786141.0,-2146111.0,-2652692.0,...,-5.700038e+06,-7.926201e+06,-8.691129e+06,-8.916872e+06,-9.394348e+06,-1.042939e+07,-1.043543e+07,-1.037372e+07,-1.076189e+07,-5.789176e+06

In [117]:
import plotly.express as px

fig = px.bar(
    df2,
    x="Year",
    y="Value",
    color="Counterparty sector",
)

fig.update_layout(
    plot_bgcolor='white',
    width=800,
    height=500,
    margin=dict(b=100),   # Extra bottom space
    legend=dict(
        orientation="h",
        y=-0.3,           # Move legend further down
        x=0.5,
        xanchor="center",
        yanchor="top"
    )
)

fig.add_annotation(
    xref="paper", yref="paper",
    x=0.02, y=0.1,
    text="(-) Liabilities",
    showarrow=False,
    font=dict(size=12)
)

fig.add_annotation(
    xref="paper", yref="paper",
    x=0.02, y=0.9,
    text="(+) Claims",
    showarrow=False,
    font=dict(size=12)
)

fig.update_yaxes(title_text=None)

fig.show()

In [123]:
import pandas as pd

urls = ["https://stats.bis.org/api/v2/data/dataflow/BIS/WS_LBS_D_PUB/1.0/.S.C.A.TO1.A.5J.A.AT+AU+BE+CA+CH+DE+DK+ES+FI+FR+GB+GR+HK+IE+IT+JP+KR+LU+NL+SE+TW+US.A.AM+BD+GE+ID+IL+IN+KR+KZ+LB+LK+MY+PH+PK+TH.N?format=csv"]

df = pd.concat([pd.read_csv(url) for url in urls])
df

,FREQ,L_MEASURE,L_POSITION,L_INSTR,L_DENOM,L_CURR_TYPE,L_PARENT_CTY,L_REP_BANK_TYPE,L_REP_CTY,L_CP_SECTOR,...,AVAILABILITY,TITLE_GRP,TIME_FORMAT,COLLECTION,ORG_VISIBILITY,TIME_PERIOD,OBS_VALUE,OBS_STATUS,OBS_CONF,OBS_PRE_BREAK
0,Q,S,C,A,TO1,A,5J,A,DK,A,...,K,NaN,NaN,E,E,1983-Q4,1.0,A,F,NaN
1,Q,S,C,A,TO1,A,5J,A,DK,A,...,K,NaN,NaN,E,E,1985-Q1,1.0,A,F,NaN
2,Q,S,C,A,TO1,A,5J,A,DK,A,...,K,NaN,NaN,E,E,1985-Q2,1.0,A,F,NaN
3,Q,S,C,A,TO1,A,5J,A,DK,A,...,K,NaN,NaN,E,E,1985-Q3,2.0,A,F,NaN
4,Q,S,C,A,TO1,A,5J,A,DK,A,...,K,NaN,NaN,E,E,1985-Q4,2.0,A,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40894,Q,S,C,A,TO1,A,5J,A,DE,A,...,K,NaN,NaN,E,E,2024-Q2,413.0,A,F,NaN
40895,Q,S,C,A,TO1,A,5J,A,DE,A,...,K,NaN,NaN,E,E,2024-Q3,416.0,A,F,NaN
40896,Q,S,C,A,TO1,A,5J,A,DE,A,...,K,NaN,NaN,E,E,2024-Q4,375.0,A,F,NaN
40897,Q,S,C,A,TO1,A,5J,A,DE,A,...,K,NaN,NaN,E,E,2025-Q1,387.0,A,F,NaN
40898,Q,S,C,A,TO1,A,5J,A,DE,A,...,K,NaN,NaN,E,E,2025-Q2,394.0,A,F,NaN

In [ ]:
import pycountry

def code_to_country(code):
    country = pycountry.countries.get(alpha_2=code.upper())
    return country.name if country else None

cty_code = df['L_REP_CTY'].unique().tolist() + df['L_CP_COUNTRY'].unique().tolist()
cty_code_dict = {code: code_to_country(code) for code in cty_code}

col_use = ['L_REP_CTY','TIME_PERIOD','OBS_VALUE']
df2 = df[col_use].copy()
df2.replace(cty_code_dict, inplace=True)

rename_col = ['Reporting country', 'Period','Value']
df2 = df2.rename(columns={k:v for k,v in zip(df2.columns, rename_col)})

col = df2.columns.to_list()
df2 = df2.groupby(by = ['Reporting country', 'Period']).sum()
df2.reset_index(inplace=True)
df2 = df2[df2['Period'].str[:4] >= '2005']
df2.reset_index(drop=True,inplace=True)
df2

     Reporting country   Period    Value
0            Australia  2005-Q1   2250.0
1            Australia  2005-Q2   1825.0
2            Australia  2005-Q3   1747.0
3            Australia  2005-Q4   1984.0
4            Australia  2006-Q1   1890.0
...                ...      ...      ...
1772     United States  2024-Q2  41785.0
1773     United States  2024-Q3  44635.0
1774     United States  2024-Q4  44756.0
1775     United States  2025-Q1  46483.0
1776     United States  2025-Q2  46964.0

[1777 rows x 3 columns]

In [149]:
import plotly.express as px

fig = px.bar(
    df2,
    x="Period",
    y="Value",
    color="Reporting country",
)

fig.update_layout(
    plot_bgcolor='white',
    width=800,
    height=500,
    margin=dict(b=100),   # Extra bottom space
    legend=dict(
        orientation="h",
        y=-0.3,           # Move legend further down
        x=0.5,
        xanchor="center",
        yanchor="top"
    )
)


fig.update_yaxes(title_text=None)

fig.show()

In [2]:
from datetime import date
today = date.today()

formatted_date = today.strftime("%Y-%m-%d")
formatted_date

'2025-12-10'